#!/usr/bin/env python3
"""Generate the ASIT documents from the source YAML.

    python asit/scripts/build.py

Emits (all generated — never hand-edit):
    docs/index.md            full taxonomy, one section per category
    docs/quick-reference.md  id / name / stage / causal locus / controls table
    docs/coverage.md         control-to-category matrix with gaps highlighted
    docs/asit.json           machine-readable, versioned
and refreshes the generated table of contents in README.md.

Output is deterministic (stable ordering) so CI can assert docs are in sync.

Dependencies: PyYAML.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = Path(__file__).resolve().parents[1]
TAX_DIR = ROOT / "taxonomy"
DOCS = ROOT / "docs"
README = ROOT / "README.md"

TAXONOMY_PATH = TAX_DIR / "taxonomy.yaml"
CONTROLS_PATH = TAX_DIR / "controls.yaml"
INCIDENTS_PATH = ROOT / "incidents" / "incidents.yaml"

STAGES = [
    ("PLAN", "Plan"),
    ("DESIGN", "Design"),
    ("BUILD", "Build"),
    ("TEST", "Test"),
    ("REL", "Release"),
    ("OPS", "Operate"),
    ("FOUND", "Foundational plane"),
]
STAGE_ORDER = {code: i for i, (code, _) in enumerate(STAGES)}
STAGE_NAME = dict(STAGES)

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/build.py from taxonomy/*.yaml. Do not hand-edit. -->\n"
)
TOC_BEGIN = "<!-- BEGIN GENERATED TOC -->"
TOC_END = "<!-- END GENERATED TOC -->"


def load_yaml(path: Path) -> dict:
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def sort_categories(cats: list[dict]) -> list[dict]:
    return sorted(cats, key=lambda c: (STAGE_ORDER.get(c["lifecycle_stage"], 99), c["id"]))


def clean(text: str) -> str:
    """Collapse the YAML folded-block whitespace into a single line."""
    return " ".join(str(text).split())


# --------------------------------------------------------------------------- #
# docs/index.md
# --------------------------------------------------------------------------- #
def build_index(tax, controls_by_id, incidents_by_id) -> str:
    cats = sort_categories(tax["categories"])
    out: list[str] = [GENERATED_BANNER]
    out.append("# ASIT — Taxonomy\n")
    out.append(f"Version **{tax['version']}** · updated **{tax['updated']}**\n")
    out.append(
        "Every category below is testable: an incident either meets the "
        "definition or it does not. Ids are permanent.\n"
    )

    # Legend
    out.append("## Legend\n")
    out.append("- **causal_locus** — the proximate cause class of the failure.")
    out.append("- **detection_point** — the earliest pipeline stage at which the "
               "failure is realistically catchable.")
    out.append("- **evidence_status** — `documented` (sourced in incidents.yaml), "
               "`reported_anecdotally`, or `anticipated` (no public case yet).")
    out.append("- **blast_radius** — 1–5, worst plausible outcome. Rubric:\n")
    for score in ("1", "2", "3", "4", "5"):
        out.append(f"  {score}. {clean(tax['blast_radius_rubric'][score])}")
    out.append("")

    # Table of contents
    out.append("## Categories\n")
    for code, label in STAGES:
        stage_cats = [c for c in cats if c["lifecycle_stage"] == code]
        if not stage_cats:
            continue
        out.append(f"**{label}**  ")
        out.append(
            "  ".join(
                f"[{c['id']}](#{c['id'].lower()})" for c in stage_cats
            )
        )
        out.append("")

    # Sections
    current_stage = None
    for c in cats:
        if c["lifecycle_stage"] != current_stage:
            current_stage = c["lifecycle_stage"]
            out.append(f"\n## {STAGE_NAME[current_stage]}\n")

        cid = c["id"]
        out.append(f'<a id="{cid.lower()}"></a>')
        depr = " *(deprecated)*" if c.get("status") == "deprecated" else ""
        out.append(f"### {cid} — {c['name']}{depr}\n")
        out.append(clean(c["definition"]) + "\n")

        out.append(f"- **Lifecycle stage:** {c['lifecycle_stage']}")
        out.append(f"- **Causal locus:** `{c['causal_locus']}`")
        out.append(f"- **Detection point:** `{c['detection_point']}`")
        band = clean(tax["blast_radius_rubric"][str(c["blast_radius"])])
        out.append(f"- **Blast radius:** {c['blast_radius']}/5 — {band}")
        out.append(f"- **Evidence status:** `{c['evidence_status']}`")

        out.append("- **Preconditions:**")
        for p in c["preconditions"]:
            out.append(f"  - {clean(p)}")

        # Mitigating controls
        if c["mitigating_controls"]:
            items = []
            for ctl in c["mitigating_controls"]:
                ctrl = controls_by_id.get(ctl)
                name = ctrl["name"] if ctrl else "UNKNOWN"
                items.append(f"{ctl} ({name})")
            out.append("- **Mitigating controls:** " + "; ".join(items))
        else:
            out.append("- **Mitigating controls:** _none — coverage gap_")

        # Related
        if c["related"]:
            out.append(
                "- **Related:** "
                + ", ".join(f"[{r}](#{r.lower()})" for r in c["related"])
            )

        # External mappings
        em = c.get("external_mappings") or {}
        if any(em.values()):
            parts = []
            for key, label in (
                ("owasp_llm", "OWASP LLM"),
                ("mitre_atlas", "MITRE ATLAS"),
                ("cwe", "CWE"),
                ("vaiss", "VAISS"),
            ):
                if em.get(key):
                    parts.append(f"{label}: {', '.join(em[key])}")
            out.append("- **External mappings:** " + " · ".join(parts))

        # Incident references
        if c["incident_refs"]:
            refs = []
            for iid in c["incident_refs"]:
                inc = incidents_by_id.get(iid)
                if inc:
                    refs.append(f"[{iid}]({inc['url']}) — {clean(inc['title'])}")
                else:
                    refs.append(f"{iid} (UNKNOWN)")
            out.append("- **Incidents:**")
            for r in refs:
                out.append(f"  - {r}")

        if c.get("notes"):
            out.append(f"- **Notes:** {clean(c['notes'])}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# docs/quick-reference.md
# --------------------------------------------------------------------------- #
def build_quick_reference(tax) -> str:
    cats = sort_categories(tax["categories"])
    out = [GENERATED_BANNER, "# ASIT — Quick Reference\n"]
    out.append(f"Version {tax['version']} · {tax['updated']}\n")
    out.append("| ID | Name | Stage | Causal locus | Detection | Blast | Evidence | Controls |")
    out.append("|----|------|-------|--------------|-----------|:-----:|----------|----------|")
    for c in cats:
        controls = ", ".join(c["mitigating_controls"]) or "—"
        name = c["name"] + (" *(deprecated)*" if c.get("status") == "deprecated" else "")
        out.append(
            f"| [{c['id']}](index.md#{c['id'].lower()}) | {name} | "
            f"{c['lifecycle_stage']} | `{c['causal_locus']}` | "
            f"`{c['detection_point']}` | {c['blast_radius']} | "
            f"{c['evidence_status']} | {controls} |"
        )
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- #
# docs/coverage.md
# --------------------------------------------------------------------------- #
def build_coverage(tax, controls) -> str:
    cats = [c for c in sort_categories(tax["categories"]) if c.get("status") != "deprecated"]
    controls_sorted = sorted(controls, key=lambda c: c["id"])

    # control id -> categories that cite it
    by_control: dict[str, list[dict]] = {ctl["id"]: [] for ctl in controls_sorted}
    for c in cats:
        for ctl in c["mitigating_controls"]:
            by_control.setdefault(ctl, []).append(c)

    out = [GENERATED_BANNER, "# ASIT — Control Coverage\n"]
    out.append(f"Version {tax['version']} · {tax['updated']}\n")
    out.append(
        "Maps the 13-control governance map onto the taxonomy. Two kinds of gap "
        "are surfaced, not hidden: **controls that mitigate no category** "
        "(possibly redundant, or mis-scoped) and **categories that lean on a "
        "single control** (thin, brittle coverage).\n"
    )

    # Matrix
    out.append("## Matrix\n")
    header = "| Category \\ Control | " + " | ".join(ctl["id"] for ctl in controls_sorted) + " |"
    sep = "|" + "---|" * (len(controls_sorted) + 1)
    out.append(header)
    out.append(sep)
    for c in cats:
        cells = []
        for ctl in controls_sorted:
            cells.append("●" if ctl["id"] in c["mitigating_controls"] else "")
        out.append(f"| {c['id']} | " + " | ".join(cells) + " |")
    out.append("")

    # Control -> categories
    out.append("## Controls and what they cover\n")
    out.append("| Control | Stage | Name | Categories mitigated |")
    out.append("|---------|-------|------|----------------------|")
    for ctl in controls_sorted:
        covered = by_control.get(ctl["id"], [])
        cats_str = ", ".join(c["id"] for c in covered) if covered else "**— none —**"
        out.append(
            f"| {ctl['id']} | {ctl['stage']} | {ctl['name']} | {cats_str} |"
        )
    out.append("")

    # Gaps
    out.append("## Gaps\n")
    unused = [ctl for ctl in controls_sorted if not by_control.get(ctl["id"])]
    if unused:
        out.append("**Controls mitigating no category** — redundant, or the "
                   "taxonomy is missing a failure mode they address:")
        for ctl in unused:
            out.append(f"- {ctl['id']} ({ctl['name']}, {ctl['stage']})")
    else:
        out.append("No control is entirely unused.")
    out.append("")

    nocover = [c for c in cats if not c["mitigating_controls"]]
    if nocover:
        out.append("**Categories with no mitigating control** — real coverage gaps:")
        for c in nocover:
            out.append(f"- {c['id']} ({c['name']})")
    else:
        out.append("Every category maps to at least one control.")
    out.append("")

    thin = [c for c in cats if len(c["mitigating_controls"]) == 1]
    if thin:
        out.append("**Categories mitigated by a single control** — brittle; one "
                   "control failing leaves the mode uncovered:")
        for c in thin:
            out.append(f"- {c['id']} ({c['name']}) → {c['mitigating_controls'][0]}")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# docs/asit.json
# --------------------------------------------------------------------------- #
def build_json(tax, controls, incidents) -> str:
    payload = {
        "version": tax["version"],
        "updated": tax["updated"],
        "generated_from": "taxonomy/taxonomy.yaml",
        "blast_radius_rubric": {k: clean(v) for k, v in tax["blast_radius_rubric"].items()},
        "controls": controls,
        "incidents": incidents,
        "categories": sort_categories(tax["categories"]),
    }
    return json.dumps(
        payload, indent=2, ensure_ascii=False, sort_keys=False, default=str
    ) + "\n"


# --------------------------------------------------------------------------- #
# README TOC
# --------------------------------------------------------------------------- #
def build_readme_toc(tax) -> str:
    cats = sort_categories(tax["categories"])
    lines = [TOC_BEGIN, "### Taxonomy at a glance", ""]
    for code, label in STAGES:
        stage_cats = [c for c in cats if c["lifecycle_stage"] == code]
        if not stage_cats:
            continue
        lines.append(f"- **{label}**")
        for c in stage_cats:
            depr = " _(deprecated)_" if c.get("status") == "deprecated" else ""
            lines.append(
                f"  - [{c['id']}](docs/index.md#{c['id'].lower()}) "
                f"{c['name']}{depr}"
            )
    lines.append("")
    lines.append(TOC_END)
    return "\n".join(lines)


def update_readme(tax) -> None:
    text = README.read_text(encoding="utf-8")
    if TOC_BEGIN not in text or TOC_END not in text:
        print("  warning: README has no TOC markers; skipping TOC update")
        return
    pre = text.split(TOC_BEGIN)[0]
    post = text.split(TOC_END)[1]
    README.write_text(pre + build_readme_toc(tax) + post, encoding="utf-8")


def main() -> int:
    tax = load_yaml(TAXONOMY_PATH)
    controls = load_yaml(CONTROLS_PATH).get("controls", [])
    incidents = load_yaml(INCIDENTS_PATH).get("incidents", [])
    controls_by_id = {c["id"]: c for c in controls}
    incidents_by_id = {i["id"]: i for i in incidents}

    DOCS.mkdir(exist_ok=True)
    (DOCS / "index.md").write_text(
        build_index(tax, controls_by_id, incidents_by_id), encoding="utf-8"
    )
    (DOCS / "quick-reference.md").write_text(build_quick_reference(tax), encoding="utf-8")
    (DOCS / "coverage.md").write_text(build_coverage(tax, controls), encoding="utf-8")
    (DOCS / "asit.json").write_text(build_json(tax, controls, incidents), encoding="utf-8")
    update_readme(tax)

    print(
        f"Built docs for {len(tax['categories'])} categories, "
        f"{len(controls)} controls, {len(incidents)} incidents."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
